version: "3.9"

services:
  db:
    image: postgres
    container_name: insy-postgres
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - 5432:5432